### PR TITLE
converters/html/converter.py: make use of the ijson package to signif…

### PR DESCRIPTION
**Pull request by Natorator**
…icantly reduce memory usage.

I had a problem using this converter gobbling up all 16GB of my ram and crashing before writing a single file. Switching from the json package to ijson allowed each conversation thread to be processed one at a time, and solved the problem handily.

### CODE REVIEW

**Comment by hydrargyrum** [comment]
Thanks @Natorator for this PR, this is very interesting!

I have a request though. Since this script had no third party dependency before, and considering this PR introduces a change for uncommon cases, I'd rather make the dependency optional. If `ijson` is installed, it's used to parse and process incrementally. If it's not installed, the script should work as before, parsing everything upfront.
A suggestion to do so: the `import ijson` should be in a `try..except`. Maybe within a function that basically wraps/reimplements "ijson.items" but works with and without `ijson`: with `ijson`, it calls it, and without `ijson`, it would return the same elements as `ijson` but simply would not be incremental, using standard `json`.

Do you have some spare time to do it yourself, or do you prefer I merge your PR and do the modifications myself afterwards?

**Comment by Natorator** [comment]
That sounds reasonable. 

I do have time (between gigs at present), but I also have other priorities, so I may not implement this particularly quickly. I'd say leave the PR unmerged, and we'll see who gets to it first. 

Thanks!

**Comment by hydrargyrum** [comment]
I now have some code to do it. Do you mind if I merge your commit (actually I'll rebase it on other work I've been doing) and then add the suggested modifications in another commit?

**Comment by hydrargyrum** [comment]
So I merged your commit and made ijson optional as said, thanks @Natorator !

**Pull request closed without merging**
